name: Deploy TaskVision Frontend

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev or prod)'
        required: true
        default: dev
        type: choice
        options: [dev, prod]

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || github.ref_name == 'main' && 'prod' || 'dev' }}

    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || github.ref_name == 'main' && 'prod' || 'dev' }}
      AWS_REGION: us-east-1
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g cross-env dotenv-cli

      - name: Build frontend
        run: |
          cp .env.${{ env.ENVIRONMENT }} .env.local
          npm run build

      - name: Verify build artifacts
        run: |
          if [ ! -d "build" ]; then
            echo "Build directory not found!"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Check if DNS record exists
        id: check-dns
        run: |
          RECORD_NAME="${{ env.ENVIRONMENT }}.${{ secrets.DOMAIN_NAME }}"
          if aws route53 list-resource-record-sets \
            --hosted-zone-id ${{ secrets.ROUTE53_ZONE_ID }} \
            --query "ResourceRecordSets[?Name=='${RECORD_NAME}.']" \
            --output text | grep -q "${RECORD_NAME}"; then
            echo "DNS_RECORD_EXISTS=true" >> $GITHUB_ENV
          else
            echo "DNS_RECORD_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Terraform Apply
        if: env.DNS_RECORD_EXISTS == 'false'
        run: terraform apply -auto-approve \
          -var="environment=${{ env.ENVIRONMENT }}" \
          -var="subdomain=${{ env.ENVIRONMENT }}" \
          -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
          -var="route53_zone_id=${{ secrets.ROUTE53_ZONE_ID }}" \
          -var="cloudfront_distribution_id=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" \
          -var="s3_bucket_name=${{ secrets.S3_BUCKET_NAME }}"
        working-directory: infra

      - name: Set S3 Bucket Name
        run: |
          if [ "${{ env.DNS_RECORD_EXISTS }}" == "true" ]; then
            echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> $GITHUB_ENV
            echo "CLOUDFRONT_DOMAIN_NAME=$(aws cloudfront get-distribution --id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --query 'Distribution.DomainName' --output text)" >> $GITHUB_ENV
          else
            cd infra
            echo "S3_BUCKET_NAME=$(terraform output -raw s3_bucket_name)" >> $GITHUB_ENV
            echo "CLOUDFRONT_DOMAIN_NAME=$(terraform output -raw cloudfront_domain_name)" >> $GITHUB_ENV
          fi

      - name: Create .env file
        run: |
          cp .env.${{ env.ENVIRONMENT }} .env
          echo "REACT_APP_AUTH0_CALLBACK_URL=https://${CLOUDFRONT_DOMAIN_NAME}/callback" >> .env

      - name: Upload build to S3
        run: aws s3 sync build/ s3://$S3_BUCKET_NAME --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
